WIDTH = 1000
HEIGHT = 600
MIDDLE_LAYOUT_WIDTH = WIDTH
MIDDLE_LAYOUT_HEIGHT = HEIGHT * 0.8

FILE_SELECTOR_LABEL_WIDTH = 800
FILE_SELECTOR_LABEL_HEIGHT = 30
FILE_SELECTOR_BUTTON_WIDTH = 100
FILE_SELECTOR_BUTTON_HEIGHT = 30

MIDDLE_RIGHT_WIDTH, MIDDLE_RIGHT_HEIGHT = MIDDLE_LAYOUT_WIDTH * 0.4, MIDDLE_LAYOUT_HEIGHT
LABEL_HEIGHT = MIDDLE_RIGHT_HEIGHT * 0.05



REMOTE_HOST_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.4
REMOTE_HOST_LABEL_HEIGHT = LABEL_HEIGHT

DATE_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.6
DATE_LABEL_HEIGHT = LABEL_HEIGHT

TIME_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.2
TIME_LABEL_HEIGHT = LABEL_HEIGHT

TIME_ZONE_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.5
TIME_ZONE_LABEL_HEIGHT = LABEL_HEIGHT

STATUS_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.2
STATUS_LABEL_HEIGHT = LABEL_HEIGHT

METHOD_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.2
METHOD_LABEL_HEIGHT = LABEL_HEIGHT

RESOURCE_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.6
RESOURCE_LABEL_HEIGHT = LABEL_HEIGHT * 1.2

SIZE_LABEL_WIDTH = MIDDLE_RIGHT_WIDTH * 0.4
SIZE_LABEL_HEIGHT = LABEL_HEIGHT

PREVIOUS_BUTTON_WIDTH = MIDDLE_RIGHT_WIDTH * 0.2
PREVIOUS_BUTTON_HEIGHT = LABEL_HEIGHT * 1.5

NEXT_BUTTON_WIDTH = MIDDLE_RIGHT_WIDTH * 0.2
NEXT_BUTTON_HEIGHT = LABEL_HEIGHT * 1.5

CLEAR_BUTTON_WIDTH = MIDDLE_RIGHT_WIDTH * 0.2
CLEAR_BUTTON_HEIGHT = LABEL_HEIGHT * 1.5

LOG_MASTER_LENGTH = 70